sudo: false
language: node_js
node_js:
- '8'
cache: false
install:
- npm install
- cd backend && npm install
- cd ../frontend && npm install
script:
- npm test
- npm run coveralls
after_script:
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js